- name: clean repo
  yum_repository:
    name: docker-ce
    state: absent
  notify: yum-clean-metadata

- include: install_docker-ce_based.yml

- name: "添加docker-ce REPO"
  shell: yum-config-manager --add-repo http://mirrors.aliyun.com/docker-ce/linux/centos/docker-ce.repo
  notify: yum-makecache

- name: install docker-ce
  yum: 
    name: docker-ce-{{docker.version}}
    state: latest

- name: "创建docker目录"
  file:
    path: "/etc/docker"
    state: directory
  ignore_errors: true

- name: create docker daemon.json
  template:
    src="daemon.json.j2"
    dest="/etc/docker/daemon.json"


- name: enable & start docker
  service: 
    name: docker 
    enabled: yes 
    state: started